sudo: required  #super user permission required always
services:
    - docker #starts up the copy of the docker

before-install:  #before rtests are run (series of setups are run before testing)
    - docker build -t adsrathore/docker-react -f Dockerfile.dev .  
    
script:
    - docker run -e CI=true adsrathore/docker-react npm run test -- --coverage    


deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-954526503946"
    bucket_path: "Docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"    

        
         